### ISSUE TITLE
Stacking limits based on plugin

### ISSUE THREAD

**Issue by dimitriosvalodimos** [NewbieOrange/clicksort#11]
Hi,

alongside ClickSort I'm also using [SimpleStack](https://github.com/Mikedeejay2/SimpleStackPlugin) on my server which allows items to stack up to 64 (e.g. eggs, signs, beds etc).
When I auto-sort the items, they split back into their original stack limits.

Is there a way for ClickSort to take the new stack limit into account?

**Comment by NewbieOrange** [comment]
Hi,

Clicksort supports [StackableItems](https://dev.bukkit.org/projects/stackableitems).

Also, can you try the 1.6.0 snapshot in #10? The performance should be better and avoid growing config size.

Let me know if there are any issues!

**Comment by dimitriosvalodimos** [comment]
I'll give 1.6.0 a try.

This is exactly what I was looking for, thank you!

**Comment by NewbieOrange** [comment]
Let me know if 1.6.0 is working fine for you and I will release it. 😃

**Comment by dimitriosvalodimos** [comment]
Oh sorry, I added 1.6.0 and since it worked I kind of forgot about it😅.

It's been working fine for me so far, thanks again!
