### ISSUE TITLE
ClickSort Metrics negatively affecting server TPS

### ISSUE THREAD

**Issue by ClementJ18** [NewbieOrange/clicksort#12]
Been seeing this massive spikes in TPS loss from time to time and using a timing report it seems to be linked to the Clicksort Metrics. Is there a way to disable Metrics for Clicksort?

![image](https://user-images.githubusercontent.com/22744199/212554484-4acf4dad-1903-4aaa-aeb4-8c3b94a356b1.png)

**Comment by NewbieOrange** [comment]
Yes, bMetrics can be globally disabled: https://bstats.org/getting-started

> Disabling bStats
> If you don't want bStats to collect data from your server, you can disable it in the bStats config file. This file can be found in the /plugins/bStats/ folder.
bStats has nearly no effect on your server's performance and the sent data is completely anonymous. The collected data is important information for plugin authors to improve their plugins and keep motivated. To value their work and effort, please keep bStats enabled.

**Comment by NewbieOrange** [comment]
Probably caused by bStats sending metrics in main thread, will try to fix this in next version by starting another thread for metrics.

If you are still seeing TPS spikes after disabling bStats, please let me know.

**Comment by ClementJ18** [comment]
Will do, thanks for the quick reply.

**Comment by NewbieOrange** [comment]
> Will do, thanks for the quick reply.

Are you using an older version of ClickSort? Since v1.6.0 the new bStats client is used and the code looks fine to me.

Older version of bStats does seem to have performance issue looking at the code, in which case you can (hopefully) just disable it.
