### ISSUE TITLE
[1.19.4] Middle Click Issue

### ISSUE THREAD

**Issue by Elrol** [NewbieOrange/clicksort#14]
I am using version 1.6.1

I was trying to use: `/clicksort click MIDDLE` and it told me that `Click method MIDDLE% is not available.`
I am thinking there is an extra `%` in the code that needs to be removed, but can't use it until it is

**Comment by NewbieOrange** [comment]
Hi, middle clicking no longer works after Minecraft 1.18 (they removed the code for it). It has been replaced with the swap key (`F` by default)
