### ISSUE TITLE
[Feature] Disable changing sort method by clicking in inventory

### ISSUE THREAD

**Issue by Elrol** [NewbieOrange/clicksort#15]
Basically what the title says.

I am wanting to disable this: 
![image](https://user-images.githubusercontent.com/12816881/236085200-8c791dec-c7ce-4023-9107-11697ac21564.png)

I would prefer the players using a command to change that.
A mod that I use, that makes moving items much easier, triggers that anytime I click and drag over an empty slot.

**Comment by NewbieOrange** [comment]
@Elrol I believe this is already doable. Just enter `/clicksort shiftclick` and you can disable it (per user). If you want it disabled by default, change the `defaults` in `config.yaml`.

If it is not working, please reopen this issue.
