### ISSUE TITLE
Adding a ignore-sorting nbt check to leave item in specific slots as Backpacks

### ISSUE THREAD

**Issue by FrancescoJacovo** [NewbieOrange/clicksort#16]
Is your feature request related to a problem? Please describe.
Add a check to block sorting to specific inventory items as Backpacks or game manager blocked in a specific hotbar slot by other plugins

Describe the solution you'd like
Add an nbt flag that plugins can add to their items to not be sorted.

**Comment by NewbieOrange** [comment]
Is adding a config to not sort items with descrption containing a configurable string enough? or do you perfer nbt tags

**Comment by FrancescoJacovo** [comment]
Nbt is better because u can hide that tags from players' view

for example:
"disable-sorting":"true"

**Comment by FrancescoJacovo** [comment]
do u agree?

**Comment by NewbieOrange** [comment]
I am thinking triggering InventorySortEvent with itemstacks to sort, and other plugins can listen to the event and remove un-sortable items from the event so ClickSort does not sort them.

edit: e.g. add `get/setSortItems()` in https://github.com/NewbieOrange/clicksort/blob/master/src/main/java/me/desht/clicksort/events/InventorySortEvent.java

**Comment by FrancescoJacovo** [comment]
Yeah also can be an alternative, when did u plan to add this?

**Comment by NewbieOrange** [comment]
> Yeah also can be an alternative, when did u plan to add this?

This week probably

**Comment by NewbieOrange** [comment]
[clicksort-master.zip](https://github.com/NewbieOrange/clicksort/files/14075157/clicksort-master.zip)

@FrancescoJacovo please try this version and see if it works for you (need to unzip). You can check the latest API for InventorySortEvent in master branch.

**Comment by FrancescoJacovo** [comment]
I cannot figure out how to do it! Can u send me a code example?

**Comment by NewbieOrange** [comment]
@FrancescoJacovo listen to `InventorySortEvent`, and using `getInventory()` & `getSortableSlots()` you can obtain the inventory and slots to be sorted. Iterate over the `Inventory` with slots from `getSortableSlots()`, and call `fixItemInSlot()` with the slots where you find the item should not be sorted.
