### ISSUE TITLE
[bug] 复制bug/dupe bug

### ISSUE THREAD

**Issue by hkkongou** [NewbieOrange/clicksort#4]
player report that auto clicking with click sort sorting key can trigger dupe bug, this cannot reproduce without click sort
玩家反馈说在连点的情况下能够复制物品

video视频:
https://youtu.be/fX0lwXdYJes

reproduce方法: (reported by player玩家反馈)
![image](https://user-images.githubusercontent.com/61608872/135053021-72d7cf57-2fdb-41c4-9ccb-50d13f6c622c.png)

**Comment by NewbieOrange** [comment]
确认，稍候放出测试版，请帮忙测试一下。

**Comment by NewbieOrange** [comment]
无法复现这个，能试一下在没有背包整理mod的情况下还能复现吗，如果不能的话，请告知一下目前MC版本和使用的背包整理插件。

**Comment by hkkongou** [comment]
> 无法复现这个，能试一下在没有背包整理mod的情况下还能复现吗，如果不能的话，请告知一下目前MC版本和使用的背包整理插件。

![image](https://user-images.githubusercontent.com/61608872/135199946-8f4dab3b-a580-4af5-96ce-e2d24113905d.png)

![image](https://user-images.githubusercontent.com/61608872/135199954-28a47ac8-9f09-4004-996a-fb009a9a3366.png)


MC 1.16.5 

另外请问测试版那里可以下载？

**Comment by NewbieOrange** [comment]
[ClickSort-dev.zip](https://github.com/NewbieOrange/clicksort/files/7259497/ClickSort-dev.zip)

尝试一下这个？jar在zip里面

**Comment by hkkongou** [comment]
> [ClickSort-dev.zip](https://github.com/NewbieOrange/clicksort/files/7259497/ClickSort-dev.zip)
> 
> 尝试一下这个？jar在zip里面

好的谢谢，我联络那个玩家测试一下，有结果的话我再通知

**Comment by hkkongou** [comment]
> > [ClickSort-dev.zip](https://github.com/NewbieOrange/clicksort/files/7259497/ClickSort-dev.zip)
> > 尝试一下这个？jar在zip里面
> 
> 好的谢谢，我联络那个玩家测试一下，有结果的话我再通知

玩家反馈说暂时测试了6-7天都没有问题
我看应该都已经修正了

**Comment by NewbieOrange** [comment]
好的，感谢反馈！如果遇到其他问题欢迎提出
