### ISSUE TITLE
排序引致部份箱子gui介面出问题

### ISSUE THREAD

**Issue by hkkongou** [NewbieOrange/clicksort#5]
简介
玩家反馈说使用 商店插件 时候，点击排序的案件进行交易行为，会导致整个交易的介面被排除而无法正常使用。

示范
使用 shopguiplus 介面

1. 打开任意商店栏目
2. 点击中键出售所有身上物品
3. 若果交易按键与排序的按键重复，将会同时续发排序，更改交易介面

![image](https://user-images.githubusercontent.com/61608872/136699364-c7b54dfb-44fc-416c-bbb0-237a6155110a.png)

![image](https://user-images.githubusercontent.com/61608872/136699400-a86deb60-26e6-4172-9c35-588a3925c86f.png)

所幸的是，介面出现显示问题并不会让玩家取出物品，但是只是无法使用介面

示范视频
https://youtu.be/SgNu0OF8yog

**Comment by NewbieOrange** [comment]
@hkkongou 请尝试测试版，需要注意修改config.yaml，加入以下行：
```yaml
ignore_plugin_inventory: true
```
[ClickSort-1.4.6-dev.zip](https://github.com/NewbieOrange/clicksort/files/7399602/ClickSort-1.4.6-dev.zip)

**Comment by hkkongou** [comment]
好的谢谢，正在测试 🙏🙏

**Comment by hkkongou** [comment]
还是不行
当按了键之后 shopguiplus 的介面还是会被系统排序 😢

**Comment by NewbieOrange** [comment]
> 
> 
> 还是不行 当按了键之后 shopguiplus 的介面还是会被系统排序 😢

嗯... 我这边没有这个插件，不太方便调试。方便的话可以加我discord：chengzi#2816

**Comment by NewbieOrange** [comment]
v1.4.6 已修复该问题
