### ISSUE TITLE
Middle Click Does Not Work

### ISSUE THREAD

**Issue by Daniel-Patino** [NewbieOrange/clicksort#7]
Middle Click to Sort does not work. I made sure I was in middle-click mode. For some reason the double-click mode still works.

**Comment by NewbieOrange** [comment]
What version of Clicksort and Bukkit are you using? Also some plugins may interfere with middle-clicks, please try again without any plugin.

**Comment by NewbieOrange** [comment]
If you are using 1.18, this is a duplicate of #9, please continue discussion there.
